In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
train=pd.read_csv("C:\\Users\\aspire 3\\Desktop\\Term 3 Project\\train.csv")

In [3]:
train.head()

ID Warehouse_block Mode_of_Shipment  Customer_care_calls  Customer_rating  \
0   1               D           Flight                    4                2   
1   2               F           Flight                    4                5   
2   3               A           Flight                    2                2   
3   4               B           Flight                    3                3   
4   5               C           Flight                    2                2   

   Cost_of_the_Product  Prior_purchases Product_importance Gender  \
0                  177                3                low      F   
1                  216                2                low      M   
2                  183                4                low      M   
3                  176                4             medium      M   
4                  184                3             medium      F   

   Discount_offered  Weight_in_gms  Reached.on.Time_Y.N  
0                44           1233                    1  
1                59           3088                    1  
2                48           3374                    1  
3                10           1177                    1  
4                46           2484                    1

In [4]:
train.groupby('Reached.on.Time_Y.N').mean()

ID  Customer_care_calls  Customer_rating  \
Reached.on.Time_Y.N                                                      
0                    7090.479486             4.147656         2.967989   
1                    4424.978364             3.991467         3.005790   

                     Cost_of_the_Product  Prior_purchases  Discount_offered  \
Reached.on.Time_Y.N                                                           
0                             214.498647         3.670424          5.545987   
1                             207.289197         3.498095         18.663721   

                     Weight_in_gms  
Reached.on.Time_Y.N                 
0                      4168.668395  
1                      3272.640104

In [5]:
train.groupby('Reached.on.Time_Y.N').median()

ID  Customer_care_calls  Customer_rating  \
Reached.on.Time_Y.N                                               
0                    7096                    4                3   
1                    3467                    4                3   

                     Cost_of_the_Product  Prior_purchases  Discount_offered  \
Reached.on.Time_Y.N                                                           
0                                    222                3                 6   
1                                    209                3                 9   

                     Weight_in_gms  
Reached.on.Time_Y.N                 
0                             4674  
1                             3231

In [6]:
train.drop(train.columns[[0]], axis=1, inplace=True)

In [7]:
train.Mode_of_Shipment[train.Mode_of_Shipment == 'Flight'] = 1
train.Mode_of_Shipment[train.Mode_of_Shipment == 'Ship'] = 2
train.Mode_of_Shipment[train.Mode_of_Shipment == 'Road'] = 3

C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [8]:
train.Product_importance[train.Product_importance == 'high'] = 1
train.Product_importance[train.Product_importance== 'low'] = 2
train.Product_importance[train.Product_importance == 'medium'] = 3

C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [9]:
train.Gender[train.Gender == 'F'] = 1
train.Gender[train.Gender== 'M'] = 2

C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [10]:
train.Warehouse_block[train.Warehouse_block == 'A'] = 1
train.Warehouse_block[train.Warehouse_block== 'B'] = 2
train.Warehouse_block[train.Warehouse_block == 'C'] = 3
train.Warehouse_block[train.Warehouse_block== 'D'] = 4
train.Warehouse_block[train.Warehouse_block== 'F'] = 5
print(train)

C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


      Warehouse_block Mode_of_Shipment  Customer_care_calls  Customer_rating  \
0                   4                1                    4                2   
1                   5                1                    4                5   
2                   1                1                    2                2   
3                   2                1                    3                3   
4                   3                1                    2                2   
5                   5                1                    3                1   
6                   4                1                    3                4   
7                   5                1                    4                1   
8                   1                1                    3                4   
9                   2                1                    3                2   
10                  3                1                    3                4   
11                  5                1  

C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """


In [11]:
train["Mode_of_Shipment"]= train["Mode_of_Shipment"].astype(int) 
train["Product_importance"]= train["Product_importance"].astype(int) 
train["Gender"]= train["Gender"].astype(int) 
train["Warehouse_block"]= train["Warehouse_block"].astype(int) 

In [12]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10999 entries, 0 to 10998
Data columns (total 11 columns):
Warehouse_block        10999 non-null int32
Mode_of_Shipment       10999 non-null int32
Customer_care_calls    10999 non-null int64
Customer_rating        10999 non-null int64
Cost_of_the_Product    10999 non-null int64
Prior_purchases        10999 non-null int64
Product_importance     10999 non-null int32
Gender                 10999 non-null int32
Discount_offered       10999 non-null int64
Weight_in_gms          10999 non-null int64
Reached.on.Time_Y.N    10999 non-null int64
dtypes: int32(4), int64(7)
memory usage: 773.4 KB


In [13]:
#import statsmodels.api as sm
X=train.drop('Reached.on.Time_Y.N',axis=1)
Y=train['Reached.on.Time_Y.N']

#logit_model=sm.Logit(Y,X)
#result=logit_model.fit()
#print(result.summary2())

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.30)

In [15]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,y_train)
predictions=model.predict(X_test)

In [16]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,predictions))

0.6375757575757576


In [17]:
from sklearn.feature_selection import RFE
rfe = RFE(model, 6)
#Transforming data using RFE
X_rfe = rfe.fit_transform(X,Y)  
#Fitting the data to model
model.fit(X_rfe,Y)
print(rfe.support_)
print(rfe.ranking_)

[False  True False  True False  True  True  True  True False]
[3 1 2 1 4 1 1 1 1 5]


In [18]:
X.head()

Warehouse_block  Mode_of_Shipment  Customer_care_calls  Customer_rating  \
0                4                 1                    4                2   
1                5                 1                    4                5   
2                1                 1                    2                2   
3                2                 1                    3                3   
4                3                 1                    2                2   

   Cost_of_the_Product  Prior_purchases  Product_importance  Gender  \
0                  177                3                   2       1   
1                  216                2                   2       2   
2                  183                4                   2       2   
3                  176                4                   3       2   
4                  184                3                   3       1   

   Discount_offered  Weight_in_gms  
0                44           1233  
1                59           3088  
2                48           3374  
3                10           1177  
4                46           2484

In [19]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.preprocessing import MinMaxScaler
#X_norm = MinMaxScaler().fit_transform(X)
X_new = SelectKBest(chi2, k=6).fit_transform(X, Y)
X_new

array([[   4,    2,  177,    3,   44, 1233],
       [   4,    5,  216,    2,   59, 3088],
       [   2,    2,  183,    4,   48, 3374],
       ...,
       [   5,    4,  242,    5,    4, 1155],
       [   5,    2,  223,    6,    2, 1210],
       [   2,    5,  155,    5,    6, 1639]], dtype=int64)

In [20]:
X=X_new
Y=train['Reached.on.Time_Y.N']

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.30)

In [22]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,y_train)
predictions=model.predict(X_test)

In [23]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,predictions))

0.6436363636363637


In [24]:
predictions

array([1, 0, 0, ..., 1, 1, 0], dtype=int64)