In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

In [2]:
train=pd.read_csv("C:\\Users\\aspire 3\\Desktop\\Term 3 Project\\train.csv")

In [3]:
train.head()

ID Warehouse_block Mode_of_Shipment  Customer_care_calls  Customer_rating  \
0   1               D           Flight                    4                2   
1   2               F           Flight                    4                5   
2   3               A           Flight                    2                2   
3   4               B           Flight                    3                3   
4   5               C           Flight                    2                2   

   Cost_of_the_Product  Prior_purchases Product_importance Gender  \
0                  177                3                low      F   
1                  216                2                low      M   
2                  183                4                low      M   
3                  176                4             medium      M   
4                  184                3             medium      F   

   Discount_offered  Weight_in_gms  Reached.on.Time_Y.N  
0                44           1233                    1  
1                59           3088                    1  
2                48           3374                    1  
3                10           1177                    1  
4                46           2484                    1

In [4]:
train.drop(train.columns[[0]], axis=1, inplace=True)

In [5]:
train.Mode_of_Shipment[train.Mode_of_Shipment == 'Flight'] = 1
train.Mode_of_Shipment[train.Mode_of_Shipment == 'Ship'] = 2
train.Mode_of_Shipment[train.Mode_of_Shipment == 'Road'] = 3
print(train)

      Warehouse_block Mode_of_Shipment  Customer_care_calls  Customer_rating  \
0                   D                1                    4                2   
1                   F                1                    4                5   
2                   A                1                    2                2   
3                   B                1                    3                3   
4                   C                1                    2                2   
5                   F                1                    3                1   
6                   D                1                    3                4   
7                   F                1                    4                1   
8                   A                1                    3                4   
9                   B                1                    3                2   
10                  C                1                    3                4   
11                  F                1  

C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [6]:
train.Product_importance[train.Product_importance == 'high'] = 1
train.Product_importance[train.Product_importance== 'low'] = 2
train.Product_importance[train.Product_importance == 'medium'] = 3
print(train)

      Warehouse_block Mode_of_Shipment  Customer_care_calls  Customer_rating  \
0                   D                1                    4                2   
1                   F                1                    4                5   
2                   A                1                    2                2   
3                   B                1                    3                3   
4                   C                1                    2                2   
5                   F                1                    3                1   
6                   D                1                    3                4   
7                   F                1                    4                1   
8                   A                1                    3                4   
9                   B                1                    3                2   
10                  C                1                    3                4   
11                  F                1  

C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [7]:
train.Gender[train.Gender == 'F'] = 1
train.Gender[train.Gender== 'M'] = 2
print(train)

      Warehouse_block Mode_of_Shipment  Customer_care_calls  Customer_rating  \
0                   D                1                    4                2   
1                   F                1                    4                5   
2                   A                1                    2                2   
3                   B                1                    3                3   
4                   C                1                    2                2   
5                   F                1                    3                1   
6                   D                1                    3                4   
7                   F                1                    4                1   
8                   A                1                    3                4   
9                   B                1                    3                2   
10                  C                1                    3                4   
11                  F                1  

C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [8]:
train.Warehouse_block[train.Warehouse_block == 'A'] = 1
train.Warehouse_block[train.Warehouse_block== 'B'] = 2
train.Warehouse_block[train.Warehouse_block == 'C'] = 3
train.Warehouse_block[train.Warehouse_block== 'D'] = 4
train.Warehouse_block[train.Warehouse_block== 'F'] = 5
print(train)

C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


      Warehouse_block Mode_of_Shipment  Customer_care_calls  Customer_rating  \
0                   4                1                    4                2   
1                   5                1                    4                5   
2                   1                1                    2                2   
3                   2                1                    3                3   
4                   3                1                    2                2   
5                   5                1                    3                1   
6                   4                1                    3                4   
7                   5                1                    4                1   
8                   1                1                    3                4   
9                   2                1                    3                2   
10                  3                1                    3                4   
11                  5                1  

C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\aspire 3\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """


In [9]:
X=train.drop('Reached.on.Time_Y.N',axis=1)
Y=train['Reached.on.Time_Y.N']

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.30)

In [11]:
#from sklearn.preprocessing import StandardScaler 
#sc_x = StandardScaler() 
#X_train = sc_x.fit_transform(X_train)  
#X_test = sc_x.transform(X_test) 

In [12]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=20, random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

C:\Users\aspire 3\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [13]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred.round(),normalize=True))

0.6527272727272727


In [14]:
regressor.feature_importances_

array([0.05440181, 0.03229454, 0.04502493, 0.05443224, 0.17123766,
       0.05954422, 0.03103044, 0.02116859, 0.29953498, 0.2313306 ])

In [15]:
import matplotlib.pyplot as plt

importances = regressor.feature_importances_
indices = np.argsort(importances)
features = train.columns[0:10]
plt.figure(1)
plt.title('Feature Importances')
plt.barh(range(len(indices)), importances[indices], color='b', align='center')
plt.yticks(range(len(indices)), features[indices])
plt.xlabel('Relative Importance')

Text(0.5,0,'Relative Importance')

In [16]:
from sklearn.feature_selection import RFE
rfe = RFE(regressor, 6)
#Transforming data using RFE
X_rfe = rfe.fit_transform(X,Y)  
#Fitting the data to model
regressor.fit(X_rfe,Y)
print(rfe.support_)
print(rfe.ranking_)

[ True False False  True  True  True False False  True  True]
[1 3 2 1 1 1 4 5 1 1]


In [17]:
X.head()

Warehouse_block Mode_of_Shipment  Customer_care_calls  Customer_rating  \
0               4                1                    4                2   
1               5                1                    4                5   
2               1                1                    2                2   
3               2                1                    3                3   
4               3                1                    2                2   

   Cost_of_the_Product  Prior_purchases Product_importance Gender  \
0                  177                3                  2      1   
1                  216                2                  2      2   
2                  183                4                  2      2   
3                  176                4                  3      2   
4                  184                3                  3      1   

   Discount_offered  Weight_in_gms  
0                44           1233  
1                59           3088  
2                48           3374  
3                10           1177  
4                46           2484

In [18]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.preprocessing import MinMaxScaler
#X_norm = MinMaxScaler().fit_transform(X)
X_new = SelectKBest(chi2, k=6).fit_transform(X, Y)
X_new

array([[4.000e+00, 2.000e+00, 1.770e+02, 3.000e+00, 4.400e+01, 1.233e+03],
       [4.000e+00, 5.000e+00, 2.160e+02, 2.000e+00, 5.900e+01, 3.088e+03],
       [2.000e+00, 2.000e+00, 1.830e+02, 4.000e+00, 4.800e+01, 3.374e+03],
       ...,
       [5.000e+00, 4.000e+00, 2.420e+02, 5.000e+00, 4.000e+00, 1.155e+03],
       [5.000e+00, 2.000e+00, 2.230e+02, 6.000e+00, 2.000e+00, 1.210e+03],
       [2.000e+00, 5.000e+00, 1.550e+02, 5.000e+00, 6.000e+00, 1.639e+03]])

In [19]:
X=X_new
Y=train['Reached.on.Time_Y.N']

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.30)

In [21]:
regressor1 = RandomForestRegressor(n_estimators=20, random_state=0)
regressor1.fit(X_train, y_train)
pred = regressor1.predict(X_test)

In [22]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,pred.round()))

0.6642424242424242
